# ensure metric server is available for HPA
# HPA = Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.microservice.name }}-hpa
  namespace: {{ .Values.microservice.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.microservice.name }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # when CPU utilization exceeds 50%, HPA will scale up the number of pods and scale down when it goes below 50%
