apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  password: <Password> # set this if you have front end env, this is base64 encoded. You can use echo -n 'password' | base64 to get the encoded value.
# instead of data can also pass stringData , then wont get base64 encoded
#stringData:
  #MONGODB_URI: {{}}