microservice: ## general serivce details
  name: grade-submission-api
  namespace: grade-submission
  replicas: 3

workload: ## container specific configurations
  image: <Image>
  port: 3000
  livenessDelay: 15
  resources:
    memory: "128Mi"
    cpu: "128m"

env: ## environment Variables
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"

secrets:
  MONGODB_USER: "YWRtaW4="
  MONGODB_PASSWORD: "cm9vdHBhc3N3b3Jk"
  MONGODB_URI: "mongodb://mongodb.mongodb.svc.cluster.local:27017/" # authentication for mongodb stateful service using helm chart is disabled so no need now.

# to check if values are properly getting injected type this command in root director where
# Chart.yaml and values.yaml is
# helm template .


# to create a package
# helm package .

# then to install the package
# helm install <package name tyou want to give like "grade-submission-api"> <package created from helm package .> -n <namespace>
# helm install grade-submission-api grade-submission-api-1.0.0.tgz -n grade-submission

# to uninstall
# helm uninstall <name given>
# helm uninstall grade-submission-api

# then can check all pods, services, pvc, deployments,configmaps, secrets in the namespace

# to see list of all helm releases
# helm list -A

# after changin to template or values.yaml or Chart.yaml,instead of uninstalling the entire package, you can simply
# helm package . 
# helm upgrade <package name> <package created with new version as per Chart.yaml> -n <namespace>

# or can directly skip packaging stage and do in the directory as
# helm upgrade <package name given > . -n <namespace>
# helm upgrade grade-submission-api . -n grade-submission

# ensure to always change version before upgrading in Chart.yaml

# to rollback to previous revision
# helm rollback <package name> revision number -n <namespace>
# helm rollback grade-submission-api 2 -n grade-submission