apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-portal # query pods with this label and manage them
  strategy:
    type: RollingUpdate
    rollUpdate:
      maxUnavailable: 50%
      maxSurge: 1 ## ensure max of 4 pods are created as update is on the process.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
      - name: grade-submission-api
        image: <Image> # say this image has a endpoint called healthz and readyz to check for liveliness and readiness
        livenessProbe: # app sends 200 reponse, healthy. 500 response then not healthy (atleast 1 negative then).
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15 # while the app is booting up, then would throw error. Giving application time to startup.
          periodSeconds: 5 # keep checking for healthyness every 5 seconds.
        readinessProbe: # checks if application is successfully able to fetch external db/api otherwise stop traffic from coming
          httpGet:
            path: /readyz 
            port: 3000
          initialDelaySeconds: 15 # not needed for readinessProbe
          periodSeconds: 5 # every 5 second will hit to check
        env:
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
        ports:
          - containerPort:  3000

# so now we can delete grade-submission-api.yaml as this will manage them. But, we do need the services separately.
# so the service will distribute the traffic to one of the three pods.
# liveliness checks if server is running, if error or not running k8s will restart
# readyness checks if the application is able to communicate with other external services like external DB or apis. If not then k8s will
# prevent traffic from getting to the pods