apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data: # kubectl aassumes its base64 encoded, so we need to encode the values before putting them here.
  MONGODB_USER: "YWRtaW4="
  MONGODB_PASSWORD: "cm9vdHBhc3N3b3Jk"