apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data: # kubectl aassumes its base64 encoded, so we need to encode the values before putting them here.
  MONGODB_USER: {{ .Values.secrets.MONGODB_USER }}
  MONGODB_PASSWORD: {{ .Values.secrets.MONGODB_PASSWORD }}