apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-portal-secret
  namespace: grade-submission
type: Opaque
data:
  password: <Password> # set this if you have front end env, this is base64 encoded. You can use echo -n 'password' | base64 to get the encoded value.
