apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="
  MONGO_INITDB_ROOT_PASSWORD: "cm9vdHBhc3N3b3Jk"

# to convert password to base64 encoded value, use echo -n 'rootpassword' | base64